spring:
  application:
    name: enrollment-service
  config:
    import: optional:configserver:http://configuser:configpass@localhost:8888/api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.config.client: DEBUG