server:
  port: 8885
  servlet:
    context-path: /api

spring:
  application:
    name: enrollment-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.100.197:5436/nkbost-enrollment-db
    username: postgres
    password: Postgres2025!
    driver-class-name: org.postgresql.Driver
    connectionTimeout: 30000
    idleTimeout: 30000
    max-open-prepared-statements: 250
    maxLifetime: 2000000
    maximumPoolSize: 5
    minimumIdle: 3
    pool-prepared-statements: true
    poolName: SpringBootHikariCP
    hikari:
      connection-timeout: '60000'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration #, classpath:db/callback

springdoc:
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true

resilience4j:
  retry:
    instances:
      employeeService:
        max-attempts: 3
        wait-duration: 500ms
      courseService:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      employeeService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
      courseService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
  bulkhead:
    instances:
      employeeService:
        max-concurrent-calls: 5
      courseService:
        max-concurrent-calls: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    io.github.resilience4j: INFO
    br.com.nttdata.nttskillboost.employeeservice.infrastructure.resilience.Resilience4jEventLogger: DEBUG
    br.com.nttdata.nttskillboost.employeeservice.adapters.api.controller.EmployeeController: DEBUG
    br.com.nttdata.nttskillboost.courseservice: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.bulkhead: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG
